version: "3.7"

networks:
    tasks:

services:
    tasks-db:
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: tasks
            POSTGRES_DB: tasks
        volumes:
            - "./db:/var/lib/postgresql/data"
        networks:
            - tasks

    tasks-queue:
        image: redis:7-alpine
        networks:
          - tasks
    tasks-backend:
        build:
            context: ../..
            dockerfile: docker/development/Dockerfile
        volumes:
            - "../..:/app"
        ports:
            - "8000:8000"
        networks:
            - tasks
        depends_on:
            - tasks-db
        command: "/app/tools/run-development.sh"
