# This tasks-collector.ini is used for manual testing.
# If you run any cli/... commands from this directory
# you automatically will be pointed to a Docker instance
# running the development environment.

[Tasks]

url = http://localhost:8000
user = django
password = django

[Display]
observation_list_count = 20
