# Generated by Django 4.2.30 on 2026-06-04 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rewards", "0006_reward_emoji"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="ChallengeStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("ne", models.PositiveSmallIntegerField(default=0)),
                ("fi", models.PositiveSmallIntegerField(default=0)),
                ("te", models.PositiveSmallIntegerField(default=0)),
                ("si", models.PositiveSmallIntegerField(default=0)),
                ("is_completion", models.BooleanField(default=False)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="enfp.challenge",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rewards.reward"
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("Ne", "Extraverted Intuition (Ne)"),
                            ("Fi", "Introverted Feeling (Fi)"),
                            ("Te", "Extraverted Thinking (Te)"),
                            ("Si", "Introverted Sensing (Si)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("published", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-published",),
                "indexes": [
                    models.Index(
                        fields=["function", "published"],
                        name="enfp_elemen_functio_497d56_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChallengeStageCompleted",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enfp.challengestage",
                    ),
                ),
            ],
            options={
                "ordering": ("-completed_at",),
            },
        ),
    ]
