# Generated by Django 3.2.12 on 2022-07-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_reward_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='choose_one',
            field=models.BooleanField(default=True, help_text='Unselect to get all items from reward table', verbose_name='OR'),
        ),
    ]
