# Generated by Django 3.2.12 on 2022-07-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_reward_choose_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claimed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.JSONField(blank=True, null=True)),
                ('claimed_date', models.DateField(blank=True, help_text='Claimed', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarded_for', models.CharField(blank=True, max_length=255, null=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.reward')),
            ],
        ),
    ]
