# Generated by Django 3.2.12 on 2022-07-31 08:25

from django.db import migrations, models
import tasks.apps.rewards.models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_claim_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimed',
            name='claimed',
            field=models.JSONField(blank=True, decoder=tasks.apps.rewards.models.CRJsonDecoder, encoder=tasks.apps.rewards.models.DataclassJSONEncoder, null=True),
        ),
    ]
