# Generated by Django 3.2.14 on 2022-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_claimed_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='emoji',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
