# Generated by Django 2.2.6 on 2019-10-30 18:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import tasks.apps.tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=tasks.apps.tree.models.default_state),
        ),
    ]
