# Generated by Django 2.2.6 on 2019-10-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20191030_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-date_started',)},
        ),
    ]
