# Generated by Django 2.2.6 on 2019-11-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20191030_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
