# Generated by Django 2.2.6 on 2020-01-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20191227_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('focus', models.TextField(blank=True, null=True)),
                ('want', models.TextField(blank=True, null=True)),
                ('in_sync', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('good', models.TextField(blank=True, null=True)),
                ('better', models.TextField(blank=True, null=True)),
                ('best', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
