# Generated by Django 2.2.6 on 2020-01-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_plan_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tree.Thread'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tree.Thread'),
            preserve_default=False,
        ),
    ]
