# Generated by Django 2.2.6 on 2020-01-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20200111_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('situation', models.TextField(blank=True, help_text='What happened?', null=True)),
                ('interpretation', models.TextField(blank=True, help_text='How you saw it, what you felt?', null=True)),
                ('approach', models.TextField(blank=True, help_text='How should I approach it in the future?', null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Thread')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.ObservationType')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
