# Generated by Django 3.0.3 on 2020-03-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_observation_observationtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='reflection',
            name='dreamstate',
            field=models.BooleanField(default=False, help_text='Were you in a dream-like state, away from the real?'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='approach',
            field=models.TextField(blank=True, help_text='How should you approach it in the future?', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='focus',
            field=models.TextField(blank=True, help_text='What is your primary focus?', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='want',
            field=models.TextField(blank=True, help_text='What feelings/thoughts/desires are currently on your mind?', null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='best',
            field=models.TextField(blank=True, help_text='What do you need to do if you want to be the best version of yourself?', null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='better',
            field=models.TextField(blank=True, help_text='How could you improve? What could you do better?', null=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='good',
            field=models.TextField(blank=True, help_text='What did you do well today?', null=True),
        ),
    ]
