# Generated by Django 3.2.10 on 2021-12-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_observation_date_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(help_text='Update')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.observation')),
            ],
        ),
    ]
