# Generated by Django 3.2.12 on 2022-07-31 04:08

from django.db import migrations, models
import tasks.apps.tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.JSONField(blank=True, default=tasks.apps.tree.models.default_state),
        ),
    ]
