# Generated by Django 3.2.16 on 2024-02-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0014_create_boardcommitted_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='date_closed',
        ),
    ]
