# Generated by Django 3.2.16 on 2024-02-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0016_remove_reflection_dreamstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='in_sync',
        ),
    ]
