# Generated by Django 3.2.16 on 2024-02-26 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0018_habit_habittracked'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableHabitsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('line', models.TextField(blank=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.thread')),
            ],
        ),
    ]
