# Generated by Django 3.2.16 on 2024-03-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0019_editablehabitsline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationUpdated',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('comment', models.TextField(help_text='Update')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.observation')),
            ],
            bases=('tree.event',),
        ),
    ]
