# Generated by Django 3.2.16 on 2024-03-28 20:31

from django.db import migrations

from tasks.apps.tree.utils.datetime import aware_from_date


def forwards_func(apps, schema_editor):
    ObservationUpdated = apps.get_model("tree", "ObservationUpdated")
    Update = apps.get_model("tree", "Update")

    db_alias = schema_editor.connection.alias

    for update in Update.objects.using(db_alias):
        ObservationUpdated.objects.create(
            observation=update.observation,
            thread_id=update.observation.thread_id,
            comment=update.comment,
            published=aware_from_date(update.pub_date),
        )
    
    Update.objects.using(db_alias).all().delete()


def reverse_func(apps, schema_editor):
    ObservationUpdated = apps.get_model("tree", "ObservationUpdated")
    Update = apps.get_model("tree", "Update")
    Thread = apps.get_model("tree", "Thread")
    db_alias = schema_editor.connection.alias

    for update in ObservationUpdated.objects.using(db_alias):
        Update.objects.create(
            observation=update.observation,
            comment=update.comment,
            pub_date=update.published.date(),
        )

    ObservationUpdated.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0021_alter_update_pub_date'),
    ]

    operations = [
         migrations.RunPython(forwards_func, reverse_func),
    ]
