# Generated by Django 3.2.16 on 2024-03-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0022_auto_20240328_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
