# Generated by Django 3.2.16 on 2024-03-28 21:22

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Event = apps.get_model('tree', 'Event')

    BoardCommitted = apps.get_model('tree', 'BoardCommitted')
    HabitTracked = apps.get_model('tree', 'HabitTracked')
    ObservationUpdated = apps.get_model('tree', 'ObservationUpdated')

    ContentType = apps.get_model('contenttypes', 'ContentType')

    db_alias = schema_editor.connection.alias

    for model in (BoardCommitted, HabitTracked, ObservationUpdated):
        new_ct = ContentType.objects.get_for_model(model)

        model.objects.using(db_alias).filter(
            polymorphic_ctype__isnull=True
        ).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tree', '0023_delete_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcommitted',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='habittracked',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='observationupdated',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='event',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_tree.event_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
