# Generated by Django 3.2.16 on 2024-07-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0024_auto_20240328_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAdded',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('comment', models.TextField(help_text='Update')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event',),
        ),
    ]
