# Generated by Django 3.2.16 on 2024-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0026_move_editable_habit_lines_to_journal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditableHabitsLine',
        ),
    ]
