# Generated by Django 3.2.16 on 2024-03-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0028_auto_20240331_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='event_stream_id',
            field=models.UUIDField(editable=False),
        ),
    ]
