# Generated by Django 3.2.16 on 2024-07-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0031_spawn_observation_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ('-pub_date', '-pk')},
        ),
        migrations.RemoveField(
            model_name='observation',
            name='date_closed',
        ),
    ]
