# Generated by Django 3.2.16 on 2024-07-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0032_auto_20240725_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='event_stream_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stream_id',
            field=models.UUIDField(editable=False),
        ),
    ]
