# Generated by Django 3.2.16 on 2024-09-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0034_quicknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationupdated',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.observation'),
        ),
    ]
