# Generated by Django 4.2.16 on 2024-09-27 22:28

from django.db import migrations

from unidecode import unidecode
from django.template.defaultfilters import slugify

import uuid

from tasks.apps.tree.uuid_generators import habit_event_stream_id, HabitEventVersion

def forwards_func(apps, schema_editor):
    Habit = apps.get_model('tree', 'Habit')
    HabitTracked = apps.get_model('tree', 'HabitTracked')

    db_alias = schema_editor.connection.alias

    for habit in Habit.objects.using(db_alias).all():
        stream_id = uuid.uuid4()

        habit.slug = slugify(unidecode(habit.name))
        habit.tagname = habit.name.lower()
        habit.event_stream_id = stream_id
        habit.save()

        HabitTracked.objects.using(db_alias).filter(
            habit=habit
        ).update(
            event_stream_id=habit_event_stream_id(habit, version=HabitEventVersion.V2)
        )


def reverse_func(apps, schema_editor):
    Habit = apps.get_model('tree', 'Habit')
    HabitTracked = apps.get_model('tree', 'HabitTracked')

    db_alias = schema_editor.connection.alias

    for habit in Habit.objects.using(db_alias).all():
        HabitTracked.objects.using(db_alias).filter(
            habit=habit
        ).update(
            event_stream_id=habit_event_stream_id(habit, version=HabitEventVersion.V1)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0036_habit_slug_habit_tagname_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
