# Generated by Django 4.2.16 on 2024-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0037_fill_habit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='tagname',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
