# Generated by Django 4.2.16 on 2024-09-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0038_alter_habit_slug_alter_habit_tagname"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
