# Generated by Django 4.2.16 on 2024-10-12 14:32

from django.db import migrations


def forward_func(apps, schema_editor):
    ObservationRecontextualized = apps.get_model('tree', 'ObservationRecontextualized')
    ObservationReinterpreted = apps.get_model('tree', 'ObservationReinterpreted')
    ObservationReflectedUpon = apps.get_model('tree', 'ObservationReflectedUpon')

    db_alias = schema_editor.connection.alias

    model_mapping = {
        ObservationRecontextualized: 'situation',
        ObservationReinterpreted: 'interpretation',
        ObservationReflectedUpon: 'approach'
    }

    for model, field in model_mapping.items():
        for instance in model.objects.using(db_alias).all():
            if getattr(instance, field).strip().replace('\r', '') == getattr(instance, f'old_{field}').strip().replace('\r', ''):
                instance.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0040_remove_empty_reflections_and_plans"),
    ]

    operations = [migrations.RunPython(forward_func, migrations.RunPython.noop)]
