# Generated by Django 4.2.16 on 2024-10-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0041_remove_unchanged_observation_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "journals",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="tree.journaladded"
                    ),
                ),
            ],
        ),
    ]
