# Generated by Django 4.2.16 on 2025-01-02 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0042_journaltag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('areas_of_concern', models.TextField(help_text='List areas of life thet give you most discomfort', verbose_name='Areas of concern')),
                ('theme', models.TextField(help_text='A phrase that captures your year', verbose_name='Theme of the year')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectedOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_by', models.DateField()),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('success_criteria', models.TextField(blank=True, help_text='List the criteria you’ll use to define success for this outcome', null=True)),
                ('breakthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.breakthrough')),
            ],
        ),
    ]
