# Generated by Django 4.2.16 on 2025-01-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0043_breakthrough_projectedoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakthrough',
            name='theme',
            field=models.CharField(help_text='A phrase that captures your year', max_length=255, verbose_name='Theme of the year'),
        ),
    ]
