# Generated by Django 3.2.16 on 2024-02-23 23:42

from django.db import migrations
from django.db.models import F


def forwards_func(apps, schema_editor):
    HabitTracked = apps.get_model("tree", "HabitTracked")
    
    db_alias = schema_editor.connection.alias

    food_habit_tracked = HabitTracked.objects.using(db_alias).filter(
        habit__slug='food'
    )

    for habit_tracked in food_habit_tracked:
        habit_tracked.occured = not habit_tracked.occured

        if habit_tracked.note:

            if habit_tracked.note.startswith('#'):
                habit_tracked.note = '!' + habit_tracked.note[1:]
            elif habit_tracked.note.startswith('!'):
                habit_tracked.note = '#' + habit_tracked.note[1:]

        habit_tracked.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0045_observationmade_before_other'),
    ]

    operations = [
        migrations.RunPython(forwards_func, forwards_func),
    ]
