# Generated by Django 4.2.18 on 2025-07-10 10:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import tasks.apps.tree.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0046_flip_food_habit_occurences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectedoutcome',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='projectedoutcome',
            name='event_stream_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='projectedoutcome',
            name='confidence_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.CreateModel(
            name='ProjectedOutcomeRescheduled',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('old_resolved_by', models.DateField()),
                ('new_resolved_by', models.DateField()),
                ('projected_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.projectedoutcome')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event', tasks.apps.tree.models.ProjectedOutcomeEventMixin),
        ),
        migrations.CreateModel(
            name='ProjectedOutcomeRedefined',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('old_name', models.CharField(blank=True, max_length=255, null=True)),
                ('new_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_description', models.TextField(blank=True, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('old_success_criteria', models.TextField(blank=True, null=True)),
                ('new_success_criteria', models.TextField(blank=True, null=True)),
                ('projected_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.projectedoutcome')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event', tasks.apps.tree.models.ProjectedOutcomeEventMixin),
        ),
        migrations.CreateModel(
            name='ProjectedOutcomeMade',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolved_by', models.DateField()),
                ('success_criteria', models.TextField(blank=True, null=True)),
                ('projected_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.projectedoutcome')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event', tasks.apps.tree.models.ProjectedOutcomeEventMixin),
        ),
        migrations.CreateModel(
            name='ProjectedOutcomeClosed',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolved_by', models.DateField()),
                ('success_criteria', models.TextField(blank=True, null=True)),
                ('projected_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.projectedoutcome')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event', tasks.apps.tree.models.ProjectedOutcomeEventMixin),
        ),
    ]
