# Generated by Django 4.2.18 on 2025-07-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0048_auto_20250710_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectedoutcomeclosed',
            name='projected_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.projectedoutcome'),
        ),
        migrations.AlterField(
            model_name='projectedoutcomemade',
            name='projected_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.projectedoutcome'),
        ),
        migrations.AlterField(
            model_name='projectedoutcomeredefined',
            name='projected_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.projectedoutcome'),
        ),
        migrations.AlterField(
            model_name='projectedoutcomerescheduled',
            name='projected_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.projectedoutcome'),
        ),
    ]
