# Generated by Django 4.2.18 on 2025-08-04 17:43

from django.db import migrations, models
import django.db.models.deletion
import tasks.apps.tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0050_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationDetached',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('other_event_stream_id', models.UUIDField(help_text='Event stream ID of the observation being detached')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event', tasks.apps.tree.models.ObservationEventMixin),
        ),
        migrations.CreateModel(
            name='ObservationAttached',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('other_event_stream_id', models.UUIDField(help_text='Event stream ID of the observation being attached')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.observation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event', tasks.apps.tree.models.ObservationEventMixin),
        ),
    ]
