# Generated by Django 4.2.18 on 2025-09-19 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

USERNAME = 'dragonee'

def update_observation_user(apps, schema_editor):
    Observation = apps.get_model('tree', 'Observation')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    Observation.objects.update(user=User.objects.get(username=USERNAME))

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0052_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_observation_user,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
