# Generated by Django 4.2.25 on 2025-10-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0054_merge_silka_into_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='tree.habit')),
            ],
            options={
                'ordering': ('keyword',),
            },
        ),
    ]
