# Generated by Django 4.2.25 on 2025-10-16 21:12

from django.db import migrations


def populate_habit_keywords(apps, schema_editor):
    """Create HabitKeyword entries from existing Habit.tagname values"""
    Habit = apps.get_model("tree", "Habit")
    HabitKeyword = apps.get_model("tree", "HabitKeyword")

    db_alias = schema_editor.connection.alias

    for habit in Habit.objects.using(db_alias).all():
        if habit.tagname:
            # Create a HabitKeyword for each habit's tagname
            HabitKeyword.objects.using(db_alias).get_or_create(
                habit=habit,
                keyword=habit.tagname
            )


def reverse_populate(apps, schema_editor):
    """Remove all HabitKeyword entries (tagname will still be preserved)"""
    HabitKeyword = apps.get_model("tree", "HabitKeyword")
    db_alias = schema_editor.connection.alias

    HabitKeyword.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0055_habitkeyword'),
    ]

    operations = [
        migrations.RunPython(populate_habit_keywords, reverse_populate),
    ]
