# Generated by Django 4.2.25 on 2025-10-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0056_populate_habit_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='tagname',
        ),
    ]
