# Generated by Django 4.2.25 on 2025-10-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0057_remove_habit_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectedoutcomeclosed',
            name='breakthrough',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tree.breakthrough'),
            preserve_default=False,
        ),
    ]
