# Generated by Django 4.2.25 on 2025-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0058_projectedoutcomeclosed_breakthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationtype',
            name='color',
            field=models.CharField(default='#ca8911', help_text='Color in hex format (e.g., #FF5733)', max_length=7),
        ),
    ]
