# Generated by Django 4.2.26 on 2025-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0059_add_color_to_observationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='habit_keywords',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='tree.habitkeyword'),
        ),
    ]
