# Generated by Django 4.2.26 on 2025-11-13 11:19

from django.db import migrations


def add_all_keywords_to_profiles(apps, schema_editor):
    """Add all existing HabitKeywords to all existing Profiles"""
    Profile = apps.get_model('tree', 'Profile')
    HabitKeyword = apps.get_model('tree', 'HabitKeyword')

    all_keywords = list(HabitKeyword.objects.all())

    for profile in Profile.objects.all():
        profile.habit_keywords.set(all_keywords)
        print(f"Added {len(all_keywords)} keywords to profile {profile.id}")


def reverse_migration(apps, schema_editor):
    """Reverse operation - clear all habit keywords from profiles"""
    Profile = apps.get_model('tree', 'Profile')

    for profile in Profile.objects.all():
        profile.habit_keywords.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0060_profile_habit_keywords'),
    ]

    operations = [
        migrations.RunPython(add_all_keywords_to_profiles, reverse_migration),
    ]
