# Generated by Django 4.2.27 on 2025-12-27 21:06

from django.db import migrations, models
import django.db.models.deletion
import tasks.apps.tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0061_add_all_keywords_to_existing_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectedOutcomeMoved',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolved_by', models.DateField()),
                ('success_criteria', models.TextField(blank=True, null=True)),
                ('new_breakthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moved_outcomes_to', to='tree.breakthrough')),
                ('old_breakthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moved_outcomes_from', to='tree.breakthrough')),
                ('projected_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.projectedoutcome')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event', tasks.apps.tree.models.ProjectedOutcomeEventMixin),
        ),
    ]
