# Generated by Django 4.2.26 on 2025-11-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0061_add_all_keywords_to_existing_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tree.event')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(help_text='Discovery details')),
                ('events', models.ManyToManyField(blank=True, related_name='discoveries', to='tree.event')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tree.event',),
        ),
    ]
