# Generated by Django 4.2.29 on 2026-03-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0063_merge_plan_want_into_focus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="want",
        ),
    ]
