# Generated by Django 4.2.29 on 2026-04-10 11:52

from django.db import migrations, models
import django.db.models.deletion
import tasks.apps.tree.models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0064_remove_plan_want"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightRefined",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tree.event",
                    ),
                ),
                (
                    "situation",
                    models.TextField(blank=True, help_text="What happened?", null=True),
                ),
                (
                    "approach",
                    models.TextField(
                        blank=True,
                        help_text="How should you approach it in the future?",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tree.observationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("tree.event", tasks.apps.tree.models.ObservationEventMixin),
        ),
    ]
