# Generated by Django 4.2.30 on 2026-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0071_event_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="map_provider",
            field=models.CharField(
                choices=[("osm", "OpenStreetMap"), ("google", "Google Maps")],
                default="osm",
                max_length=16,
            ),
        ),
    ]
