# Generated by Django 5.2.17 on 2026-09-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0075_photoadded_content_hash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardcommitted",
            options={},
        ),
        migrations.AlterModelOptions(
            name="habittracked",
            options={},
        ),
        migrations.AlterModelOptions(
            name="insightrefined",
            options={},
        ),
        migrations.AlterModelOptions(
            name="journaladded",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationattached",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationclosed",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationdetached",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationmade",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationrecontextualized",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationreflectedupon",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationreinterpreted",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observationupdated",
            options={},
        ),
        migrations.AlterModelOptions(
            name="photoadded",
            options={},
        ),
        migrations.AlterModelOptions(
            name="projectedoutcomeclosed",
            options={},
        ),
        migrations.AlterModelOptions(
            name="projectedoutcomeevolved",
            options={},
        ),
        migrations.AlterModelOptions(
            name="projectedoutcomemade",
            options={},
        ),
        migrations.AlterModelOptions(
            name="projectedoutcomemoved",
            options={},
        ),
        migrations.AlterModelOptions(
            name="projectedoutcomeredefined",
            options={},
        ),
        migrations.AlterModelOptions(
            name="projectedoutcomerescheduled",
            options={},
        ),
    ]
